// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdtyffbejxudhdaqstti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkdHlmZmJlanh1ZGhkYXFzdHRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTgwODksImV4cCI6MjA2MzIzNDA4OX0.epIUnx2pFJEeRrtYdP_tI--COy74IdYJ8_FABV5y50o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);